### PR TITLE
Fix lint issues

### PR DESCRIPTION
**Pull request by marcoshuck**
This PR fixes all the issues raised while executing the lint job in CI

### CODE REVIEW

**Comment by marcoshuck** [comment]
Lint issues have been fixed.

**Comment by AlejoAsd** [comment]
Tests are failing due to database connection issues. This isn't strictly related to this PR, but let's please fix this in another PR, merge it here, and try again.

**Comment by marcoshuck** [comment]
> Tests are failing due to database connection issues. This isn't strictly related to this PR, but let's please fix this in another PR, merge it here, and try again.

I'd like to propose a different approach. We are not merging into `main`, but to `feature/enable_ci`. What if we merge this PR there and create a new PR for the `test` issues?

**Comment by AlejoAsd** [comment]
Sounds good. Approving.

**Review by AlejoAsd — APPROVED** [review]

**Pull request merged**
